name: Generate Snake

on:
  # This will trigger the action at specific intervals or manually via the GitHub interface.
  schedule:
    # This example will trigger the action every 12 hours. You can adjust this.
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows you to manually trigger the action from GitHub's "Actions" tab.

  # Also, run when a change is pushed to the main branch
  push:
    branches:
      - main

jobs:
  # Define a job called 'build'
  build:
    runs-on: ubuntu-latest # Specifies that the job will run on an Ubuntu runner (virtual machine).

    steps:
      # Step 1: Check out the repository
      - name: Clone repo
        uses: actions/checkout@v3  # This action checks out your repository.

      # Step 2: Generate the snake files using Platane/snk GitHub Action
      - name: Generate the snake files
        uses: Platane/snk@v3  # This is the action that generates the snake GIF/SVG files.
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }} # GitHub username (you can leave this as is).
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for authentication and making changes to the repository.

      # Step 3: Show the status of the repository to verify the files to be committed.
      - name: Show build status
        run: git status  # This step shows what changes have been made, so you can verify before committing.

      # Step 4: Commit and push the generated files to the main branch
      - name: Commit and push changes to the main branch
        uses: EndBug/add-and-commit@v9  # This action helps to add and commit files to the repository.
        with:
          author_name: 'github-actions'  # Author name for the commit.
          author_email: 'github-actions@users.noreply.github.com'  # Author email for the commit.
          message: 'Update snake animations'  # Commit message.
          add: 'dist/*'  # Path to the files you want to commit (in this case, the files in the `dist/` folder).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is necessary to push the changes back to the repo.
